import type { NextPage } from 'next'
import Head from 'next/head'
import { ProductList } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kpsule | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ProductList />
      </main>
    </div>
  )
}

export default Home
